source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ColorHSPicker_Example', :exclusive => true do
  pod 'ColorHSPicker', :path => '../'
end

target 'ColorHSPicker_Tests', :exclusive => true do
  pod 'ColorHSPicker', :path => '../'

  
end
